import { NextRequest } from 'next/server';
import { requireAuth, createServerClient, createServiceClient } from '@/lib/supabase/server';
import { ApiResponse } from '@/lib/utils/response';
import { validateRequired, errorResponse } from '@/lib/utils/errors';

export const dynamic = 'force-dynamic';

// GET /api/workflows - List user's workflows
export async function GET(request: NextRequest) {
  try {
    const user = await requireAuth();
    const supabase = createServiceClient();

    // Get query params
    const { searchParams } = new URL(request.url);
    const page = parseInt(searchParams.get('page') || '1');
    const limit = parseInt(searchParams.get('limit') || '10');
    const search = searchParams.get('search') || '';

    // Calculate offset
    const offset = (page - 1) * limit;

    // Build query - include metadata for version and author info
    let query = supabase
      .from('workflows')
      .select('id, name, description, metadata, created_at, updated_at', { count: 'exact' })
      .eq('user_id', user.id)
      .order('updated_at', { ascending: false })
      .range(offset, offset + limit - 1);

    // Add search filter if provided
    if (search) {
      query = query.or(`name.ilike.%${search}%,description.ilike.%${search}%`);
    }

    const { data, error, count } = await query;

    if (error) {
      return ApiResponse.error(error.message, 500);
    }

    return ApiResponse.success({
      workflows: data || [],
      total: count || 0,
      page,
      limit,
    });
  } catch (error) {
    return errorResponse(error);
  }
}

// POST /api/workflows - Create new workflow
export async function POST(request: NextRequest) {
  try {
    const user = await requireAuth();
    
    // Use service client to bypass RLS when using Bearer token
    // This is safe because we already validated the user with requireAuth()
    const supabase = createServiceClient();
    const body = await request.json();

    const { name, description, nodes, edges, metadata } = body;

    // Validation
    validateRequired({ name, nodes, edges }, ['name', 'nodes', 'edges']);

    if (!Array.isArray(nodes) || !Array.isArray(edges)) {
      return ApiResponse.badRequest('Nodes and edges must be arrays');
    }

    // Prepare metadata with auto-generated fields
    const workflowMetadata = {
      ...(metadata || {}),
      author: user.email || user.id,
      version: 1,
      tags: metadata?.tags || [],
    };

    // Insert workflow (id, created_at, updated_at are auto-generated by database)
    const { data, error } = await supabase
      .from('workflows')
      .insert({
        user_id: user.id,
        name,
        description: description || null,
        nodes,
        edges,
        metadata: workflowMetadata,
      })
      .select()
      .single();

    if (error) {
      return ApiResponse.error(error.message, 500);
    }

    return ApiResponse.success(data, 201);
  } catch (error) {
    return errorResponse(error);
  }
}
